Bugfix/#12 fix game session
AlexBimlnk/CardGameDurak pull request #31
Opened 2022-06-26 12:48 UTC by Tigeroff2002

Исправление GameSession

2022-06-26 13:05 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/GameSession.Tests.cs
> +        exception.Should().BeNull();
Название теста говорит о том что карты не могут быть выданы при некорректных аргументах.
В тесте вообще метод не вызывается, непонятно что за тест для чего он нужен.
Судя по методу выдачи карт нужно тестировать входные параметры в виде кол-во карт в метод.
Наверное нужно будет сделать теорию через `InlineData`

2022-06-26 13:07 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +            throw new ArgumentException("Count of players can't be less " + MIN_AMOUNT_PLAYERS.ToString() + " .", nameof(players));
`$"Count of players can't be less {MIN_AMOUNT_PLAYERS}", nameof(players)`

2022-06-26 13:07 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +    /// Карту типа Suit <see cref="Suit"/>.
Suit это не карта и карта типа. Это масть. Возвращает масть типа Suit что является перечислением.

2022-06-26 13:16 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/NormalStrategy.Tests.Data.cs
> +    };
тесты на случаи когда подкинуть не можем?

2022-06-26 13:19 UTC, AlexBimlnk commented
Почему вообще в комите изменения с задачи #9?
Я мерджил с девелоп. Проверил. Этого там нет, видимо ты ветку новую отбранчевал от 9 задачи, вместо developa.
Правь коменты, ждем ПР по #9 потом уже здесь закроем.

2022-06-27 08:04 UTC, AlexBimlnk requested changes

2022-06-27 08:04 UTC, arabanas commented on CardGameDurak.Logic.Tests/GameSession.Tests.cs
> +    // не понял, как через InlineData пока сделать
Пример:
https://github.com/AlexBimlnk/CardGameDurak/blob/eb627b2cd84dc59a2f9a944c46f1d2c662a54546/CardGameDurak.Logic.Tests/Bot.Tests.cs#L29-L44

2022-06-27 08:04 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/GameSession.Tests.cs
> +        var result = countCards > 0 ? session.GiveCards(countCards) : null!;
Мы не проверяем логику в тестах, мы тестируем метод, который должен сам что то проверять и возвращать.
Просто передаем countCards и заворачиваем в эксепшен, потому что как я видел там ошибка тровнится

2022-06-27 08:04 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +    /// Возвращает масть типа Suit что является перечислением <see cref="Suit"/>.
`Возвращает масть типа <see cref="Suit"/>.`

2022-06-27 08:08 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +    /// Возвращает масть типа Suit что является перечислением <see cref="Suit"/>.
И `.` в конце предложений (на самори отсутсвует)

2022-07-01 14:19 UTC, AlexBimlnk requested changes

2022-07-01 14:19 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +        if (_players.Count < MIN_AMOUNT_PLAYERS)
Раз уж мы добавили и максимальное количество, то его тоже проверить. 
И тогда можно наверное написать `throw new ArgumentOutOfRangeException(nameof(_players.Count))`

2022-07-01 21:12 UTC, AlexBimlnk requested changes

2022-07-01 21:12 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +    /// Возвращает масть типа Suit. <see cref="Suit"/>.
Зачем две точки? Только в конце одну оставь

2022-07-01 21:12 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +        if (players.Count() < MIN_AMOUNT_PLAYERS)
лишняя проверка. В AddPlayers вся логика уже есть

2022-07-01 21:12 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/GameSession.Tests.cs
> +    [InlineData(0)]
Недостаточно данных. Что если поступить отрицательное число, что если будет слишком большое число, например 100? Эти кейсы тоже нужно прописать

2022-07-01 21:12 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/GameSession.Tests.cs
> +        exception.Should().NotBeNull();
`And.BeOfType<ArgumentOutOfRangeException>()`
Мы должны убедиться что контракт соблюдается и возвращается соотвествующая ошибка

2022-07-01 21:19 UTC, Tigeroff2002 commented on CardGameDurak.Logic.Tests/GameSession.Tests.cs
> +        exception.Should().NotBeNull();
Да, я как раз хотел это написать

2022-07-01 21:50 UTC, AlexBimlnk approved these changes

2022-07-01 21:55 UTC, merged