Features/#14 compare game sessions
AlexBimlnk/CardGameDurak pull request #37
Opened 2022-07-06 15:11 UTC by Tigeroff2002

Реализовываю сравнение игровых сессий, а конкретно переопределяю метод Equals

2022-07-06 15:28 UTC, AlexBimlnk requested changes

2022-07-06 15:28 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +
лишняя строка

2022-07-06 15:28 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +    }
Почему одни из самых отличительных атрибутов сессии - id и version не проходят сравнение?

2022-07-06 15:28 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +        if ((obj is not GameSession curSession) || (curSession is null))
```cs
if (obj is IGameSession session)
    return Equals(session);
else
   return false;
```

2022-07-06 15:28 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +    public override int GetHashCode() => base.GetHashCode();
Нет. Нужно что то вроде
`Hashcode.Combine(Id, Version)`
Возможно добавить еще атрибутов сессии в комбайн, но в целом в теории должно быть достаточно

2022-07-06 15:28 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +                    countEquals = false;
`return false`

2022-07-06 15:28 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +        var countEquals = ((Players.Count == curSession.Players.Count)
```cs
if (Players.Count != curSession.Players.Count || 
   Desktop.Count != curSession.Desktop.Count)
return false;
```

2022-07-06 15:28 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +            for (int i = 0; i < Players.Count; i++)
foreach лучше

2022-07-06 15:28 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +                if (GetPlayerCards(Players.ElementAt(i)).Count
и вообще можно попробовать сравнивать как то так, чтобы заодно проверять какие карты в руке.
```cs
if (collection1.Expect(collection2).Any()) // Если разность коллекций не 0
    return false;
```
И если мы IEquatable для карт не добавили - то нужно добавить.

2022-07-06 19:09 UTC, Tigeroff2002 commented on CardGameDurak.Logic/GameSession.cs
> +            for (int i = 0; i < Players.Count; i++)
Форичем здесь не получится сделать. Так как сравниваются соотвествующие элементы двух коллекций с одинаковыми индексами. А не просто проходится коллекция одна. Поэтому в данном случае удобней сделать так, как есть (если вообще оставлять эти циклы)

2022-07-06 19:09 UTC, Tigeroff2002 commented on CardGameDurak.Logic/GameSession.cs
> +                if (GetPlayerCards(Players.ElementAt(i)).Count
Я тоже считаю, что так лучше и лаконичнее получается. Я так и сделаю пока.

2022-07-07 13:50 UTC, AlexBimlnk requested changes

2022-07-07 13:50 UTC, arabanas commented on CardGameDurak.Logic/Card.cs
> +        if (Rank != curCard.Rank || Suit != curCard.Suit || Owner != curCard.Owner)
В таком случае, как кстати и в сравнении у GameSession непонятно как сравнивать игроков. Вероятно `IEquatable<IPlayer>` нужно применить и к `PlayerBase` вероятно

2022-07-07 13:50 UTC, AlexBimlnk commented on CardGameDurak.Logic/GameSession.cs
> +        if (Players.Except(curSession.Players).Any() || Desktop.Except(curSession.Desktop).Any())
`Players.Except(curSession.Players).Any()` не думаю что будет работать без IEquatable

Опять же. Нужны тесты. Как раз чтобы убедиться что все работает. Тесты на Equals у сессии, карт и игроков

2023-01-24 20:15 UTC, closed without merging