Features/#25 creating additional strategies
AlexBimlnk/CardGameDurak pull request #38
Opened 2022-07-13 13:55 UTC by Tigeroff2002

Добавил новые кейсы с данными для дополнительной стратегии

2022-07-19 15:55 UTC, AlexBimlnk requested changes
В [wiki](https://github.com/AlexBimlnk/CardGameDurak/wiki/%D0%98%D0%B3%D1%80%D0%BE%D0%B2%D1%8B%D0%B5-%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D0%B8) опиши стратегию

2022-07-19 15:55 UTC, AlexBimlnk commented on CardGameDurak.Logic/AdditionalStrategy.cs
> +public class AdditionalStrategy: IBotStrategy
Название стратегии лучше изменить.

2022-07-19 15:55 UTC, AlexBimlnk commented on CardGameDurak.Logic/AdditionalStrategy.cs
> +        if (deckSize > 11)
Мне кажется тут можно использовать pattern matching что то вроде:
```cs
resultCard ??= deckSize switch 
{
   > 11 => ...;
   > 4 => ...;
   _ => ... ;
}
```
Можно проверку на `null` если что в `if` вынести вместо `??=`

2022-07-19 15:55 UTC, arabanas commented on CardGameDurak.Logic/AdditionalStrategy.cs
> +        if (deckSize > 11)
Аналогично

2022-08-07 18:24 UTC, AlexBimlnk requested changes

2022-08-07 18:24 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
> +        if (desktopCards is null || desktopCards.Count == 0)
Короче тут надо все таки разбить на две ошибки. Здесь и в другой стратегии тоже, если есть такое.
На null -> `ArgumentNullException.ThrowIfNull(desktopCards);`
А потом проверка количества карт должно вызвать видимо просто `ArgumentException`

2022-08-07 18:24 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
> +                                    .Where(needClosed => !needClosed.IsTrump)
Можно не так много табов, пожалуйста
```cs
 > 11 => handCards
 [1 tab].Where(x => x.IsTrump)
        .Where(needClosed => !needClosed.IsTrump)
```

2022-08-07 18:24 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
> +                                    .Where(x => !needClosed.IsTrump)
первое Where на новую строку 1 табом.
Там где ?? на два таба уже

2022-08-07 18:24 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
> +            > 11 => resultCard ??= simpleCards.Where(x => desktopCards.Any(y => x.Rank == y.Rank))
Табы аналогично

2022-08-07 20:02 UTC, Tigeroff2002 commented on CardGameDurak.Logic/MediumStrategy.cs
> +        if (desktopCards is null || desktopCards.Count == 0)
Если менять другую стратегию, то это нужно, наверное, делать в другой ветке
Хотя можно все закомитить здесь и потом смерджить все вместе в девелоп

2022-08-07 20:08 UTC, AlexBimlnk requested changes

2022-08-07 20:08 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
> +            ArgumentNullException.ThrowIfNull(desktopCards);
Если писать так `ArgumentNullException.ThrowIfNull(desktopCards);` То `if` не нужен. Он уже проверяет и тровнит. Это решения для проверки метода в одну строчку, без if'a

2022-08-07 20:08 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
> +            throw new ArgumentException("Карт нет на столе");
Соответственно это поведение должно быть отражено в тестах

2022-08-07 20:08 UTC, AlexBimlnk commented on CardGameDurak.Logic/NormalStrategy.cs
> +            ArgumentNullException.ThrowIfNull(desktopCards);
Аналогично

2022-08-07 20:08 UTC, AlexBimlnk commented on CardGameDurak.Logic/NormalStrategy.cs
> +            throw new ArgumentException("Карт нет на столе");
Аналогично

2022-08-09 08:19 UTC, AlexBimlnk requested changes
константу вместо числа 10 в стратегии, `out var` на `out` параметрах вместо объявления их в arrange'e. Удалить лишние комментарии в тестах

2022-08-16 15:23 UTC, AlexBimlnk requested changes

2022-08-16 15:23 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/MediumStrategy.Tests.cs
> -        var botCards = Array.Empty<ICard>(); // Аналогично
Оставь `Array.Empty<ICard>();` везде

2022-08-16 15:23 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/MediumStrategy.Tests.cs
> +        ICard closedCard = null!;
не нужно объявлять

2022-08-16 15:23 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/MediumStrategy.Tests.cs
> +        ICard closedCard = null!;
не нужно объявлять

2022-08-16 15:23 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/MediumStrategy.Tests.cs
> +        var exception = Record.Exception(() => CanDefence(botCards, desktopCards, deckSize, closedCard, expectedCard, expectedResult));
Это что вообще за вызовы???

Тест должен вот так выглядеть:
```cs
[Fact(DisplayName = "Bot can not defence cause there are not hand cards")]
    [Trait("Category", "Properties")]
    public void CanNotDefenceWhenHandIsNull()
    {
        // Arrange
        var strategy = new MediumStrategy();
        var someOwnerId = 1;
        var botCards = Array.Empty<ICard>(); // Или вместо Array.Empty<ICard>(); использовать new List<ICard>();
        var desktopCards = Array.Empty<ICard>();
        var deckSize = 0;

        // Act
        var exception = Record.Exception(() =>
          strategy.TryDefence(someOwnerId, botCards, desktopCards, deckSize, out var resultCard, out var closedCard));

        // Assert
        exception.Should().NotBeNull().And.BeOfType<ArgumentException>();
    }
```
Мы что тестируем - стратегию. Методы какие должны дерагть - стратегии. Проверяем что - работу методов стратегии.
Переделать везде по аналогии на вызов непосредственно методов самой стратегии

2022-08-16 15:23 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
> +    public const int MAX_POSSIBLE_RANK_TRUMP_CARD = 10;
какой смысл делать это публичным членом? этим кто то пользоваться будет? Если да, то почему?
Соотвественно если делаем приватным то xml-doc не нужен.

2022-08-16 15:23 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
>      public bool TryAttack(
Доку нужно дополнить (везде аналогично)
```cs
/// <inheritdoc/>
/// <exception cref="ArgumentNullException" xml:lnag = "ru">
    /// Когда список карт в руке равен <see langword="null"/>.
    /// </exception>
/// <exception cref="ArgumentException" xml:lnag = "ru">
    /// Когда кол-во карт в колде меньше нуля.
    /// </exception>
    public bool TryAttack(
```
Плюс надо на null еще desktop cards проверять.

Везде исправить по аналогии написать тесты

2022-08-16 17:20 UTC, AlexBimlnk requested changes

2022-08-16 17:20 UTC, AlexBimlnk commented on CardGameDurak.Logic.Tests/MediumStrategy.Tests.cs
> +    public void CanNotDefenceWhenDeckIsLessZero()
название метода не соответствует действительности

2022-08-16 17:20 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
>      /// <inheritdoc/>
Видимо здесь должна быть документация которая написана выше непонятно для чего

2022-08-16 17:20 UTC, AlexBimlnk commented on CardGameDurak.Logic/NormalStrategy.cs
>      /// <inheritdoc/>
аналогчино

2022-08-16 17:23 UTC, AlexBimlnk requested changes

2022-08-16 17:23 UTC, AlexBimlnk commented on CardGameDurak.Logic/MediumStrategy.cs
> +    public bool TryDefence(
Не описаны исключения

2022-08-16 17:23 UTC, AlexBimlnk commented on CardGameDurak.Logic/NormalStrategy.cs
>          int ownerId,
И здесь аналогнично

2022-08-16 17:39 UTC, arabanas approved these changes

2022-08-16 20:25 UTC, merged